questions = [
    "Quel est le nombre total de clients dans la base ?",
    "Liste les noms de tous les produits.",
    "Quelle est la commande ayant le montant le plus élevé ?",
    "Quel est le total des ventes par client ?",
    "Quels produits n’ont jamais été commandés ?",
    "Quel est le chiffre d'affaires total pour chaque secteur ?",
    "Quels sont les clients ayant passé plus de 3 commandes ?",
    "Quel est le montant moyen d'une commande pour chaque client ?",
    "Combien de commandes ont été passées en 2023 ?",
    "Quel est le produit le plus vendu en quantité ?",
    "Donne le nombre de produits par catégorie.",
    "Quel est le montant total des commandes pour le mois de janvier ?",
    "Liste les clients ayant commandé un produit de la catégorie Informatique.",
    "Quel est le nombre de fournisseurs localisés en France ?",
    "Donne la liste des commandes dont le montant dépasse 1000 euros.",
    "Quel est le client qui a dépensé le plus en 2023 ?",
    "Quel est le nombre de commandes par fournisseur ?",
    "Donne la liste des produits vendus à plus de 10 clients différents.",
    "Quel est le nombre moyen de commandes par client ?",
    "Quel est le secteur qui génère le plus de chiffre d'affaires ?",
    "Donne la liste des clients n'ayant jamais passé de commande.",
    "Combien de villes différentes comptent des clients ?",
    "Quel est le produit ayant généré le plus de chiffre d'affaires en 2024 ?",
    "Donne la liste des commandes passées entre le 1er janvier et le 31 mars 2024.",
    "Combien de commandes ont été passées pour chaque produit ?",
    "Quel est le montant total des commandes pour chaque mois de 2024 ?",
    "Quels sont les produits qui n’ont jamais été vendus à des clients du secteur 'Santé' ?",
    "Donne la répartition des clients par secteur.",
    "Quel est le fournisseur ayant le plus grand nombre de produits référencés ?",
    "Liste les commandes dont le montant est compris entre 500 et 1500 euros.",
    "Combien de clients ont passé des commandes chaque année depuis 2020 ?",
    "Quel est le nombre total de produits vendus en 2023 ?",
    "Quel est le client ayant commandé le plus de produits différents ?",
    "Quel est le montant total des commandes pour chaque client et chaque mois ?",
    "Combien de commandes ont été livrées en retard ?",
    "Quel est le montant total des commandes par ville ?",
    "Liste les 10 produits les plus commandés.",
    "Quel est le produit le moins vendu ?",
    "Quel est le nombre moyen de produits par commande ?",
    "Quels sont les clients ayant commandé chez plus de 2 fournisseurs différents ?",
    "Donne la liste des produits commandés plus de 100 fois.",
    "Quel est le chiffre d'affaires total par fournisseur ?",
    "Quel est le nombre de commandes passées pour chaque catégorie de produit ?",
    "Combien de commandes ont été passées le week-end ?",
    "Quel est le montant total des commandes pour chaque année ?",
    "Liste les clients ayant passé des commandes chaque mois de 2023.",
    "Quel est le montant moyen d'une commande par secteur de client ?",
    "Donne la liste des commandes pour lesquelles le client et le fournisseur sont dans le même pays.",
    "Quels produits ont été commandés à la fois en 2023 et 2024 ?",
    "Combien de produits différents ont été commandés par secteur ?",
    "Quel est le montant total des commandes dont le client est à Paris ?",
    "Quel est le montant total des ventes par catégorie de produit ?",
    "Donne le nombre de commandes par jour de la semaine.",
    "Quel est le produit le plus commandé en janvier 2024 ?",
    "Combien de clients différents ont commandé chaque produit ?",
    "Quel est le montant total des commandes pour chaque fournisseur ?",
    "Quel est le nombre moyen de commandes par ville ?",
    "Quel est le montant total des commandes passées par les clients du secteur 'Education' ?",
    "Quels sont les produits dont le prix unitaire est supérieur à 500 euros ?",
    "Donne la liste des commandes dont le montant est inférieur à la moyenne.",
    "Quel est le client ayant commandé tous les produits d’une même catégorie ?",
    "Combien de produits différents ont été vendus à chaque client ?",
    "Quel est le fournisseur dont les produits ont généré le plus de chiffre d'affaires ?",
    "Liste les 20 plus grosses commandes de l'année dernière.",
    "Quel est le produit qui a généré le moins de chiffre d'affaires ?",
    "Donne la liste des clients qui n'ont commandé que des produits de la catégorie 'Bureautique'.",
    "Combien de commandes ont été annulées ?",
    "Quel est le montant total des commandes par jour de la semaine en 2023 ?",
    "Quel est le secteur qui a le moins de clients ?",
    "Quel est le nombre de fournisseurs par pays ?",
    "Quel est le montant total des commandes ayant été payées en espèces ?",
    "Combien de produits référencés n'ont jamais été commandés ?",
    "Donne la liste des commandes passées le jour du 1er mai.",
    "Quel est le client qui a passé la commande la plus chère ?",
    "Quel est le produit le plus vendu à Paris ?",
    "Combien de commandes ont été passées par chaque secteur de client ?",
    "Quel est le montant total des commandes pour chaque type de produit ?",
    "Donne la liste des produits commandés par plus de 5 clients différents en 2023.",
    "Quel est le chiffre d'affaires total par mois et par fournisseur ?",
    "Liste les clients ayant passé des commandes chaque trimestre de 2023.",
    "Combien de commandes ont été passées entre le 1er juin et le 30 juin ?",
    "Quel est le produit le plus commandé chaque trimestre ?",
    "Quel est le montant total des commandes pour chaque fournisseur en 2023 ?",
    "Quel est le client ayant le plus commandé chaque année ?",
    "Quel est le montant moyen des commandes par fournisseur ?",
    "Combien de commandes ont été livrées à l'heure ?",
    "Donne la liste des clients qui n'ont commandé que des produits de la catégorie 'Informatique'.",
    "Combien de fournisseurs différents ont été sollicités par chaque client ?",
    "Quel est le montant total des commandes passées par chaque secteur et chaque ville ?",
    "Liste les produits qui ont été commandés par tous les clients d'une même ville.",
    "Quel est le montant total des ventes par catégorie et par mois ?",
    "Combien de commandes ont été passées chaque mois depuis 2022 ?",
    "Quel est le client ayant dépensé le plus par trimestre ?",
    "Quel est le montant total des commandes pour chaque fournisseur et chaque mois ?",
    "Combien de clients ont commandé des produits de plus de 1000 euros ?",
    "Quel est le montant total des commandes payées par virement bancaire ?",
    "Quel est le produit dont le montant total commandé dépasse 5000 euros ?",
    "Liste les 5 produits ayant généré le plus de chiffre d'affaires en 2023.",
    "Donne la liste des commandes par fournisseur, par mois et par ville.",
    "Quel est le montant total des commandes annulées ?",
    "Quel est le nombre de clients par pays ?",
    "Quel est le montant total des ventes par produit et par fournisseur ?",
    "Quel est le montant moyen des commandes passées par les clients de Paris ?",
    "Quel est le nombre de produits référencés par fournisseur ?",
    "Combien de produits de la catégorie 'Bureautique' ont été commandés en 2024 ?",
    "Quel est le chiffre d'affaires total généré par chaque catégorie de produit chaque année ?",
    "Quel est le montant total des commandes payées en carte bancaire ?",
    "Quel est le client ayant commandé le plus souvent en janvier ?",
    "Donne la liste des produits commandés par chaque client chaque année.",
    "Quel est le fournisseur ayant vendu le plus de produits en 2024 ?",
    "Quel est le montant total des commandes pour chaque client et chaque catégorie ?",
    "Liste les clients qui ont commandé des produits de plus de 2000 euros.",
    "Quel est le produit le plus commandé chaque mois ?",
    "Combien de fournisseurs différents ont vendu des produits à chaque client ?",
    "Quel est le montant total des commandes pour chaque produit, chaque fournisseur et chaque mois ?",
    "Liste les clients qui n'ont jamais commandé de produit de la catégorie 'Informatique'.",
    "Quel est le nombre de commandes passées chaque semaine en 2023 ?",
    "Quel est le client ayant commandé le plus de produits différents par mois ?",
    "Combien de commandes ont été passées par les clients du secteur 'Santé' ?",
    "Quel est le montant moyen des commandes annulées ?",
    "Quel est le fournisseur dont les produits n'ont jamais été commandés ?",
    "Liste les commandes passées le dernier jour de chaque mois.",
    "Quel est le montant total des commandes pour chaque catégorie et chaque ville ?",
    "Combien de produits différents ont été commandés par chaque fournisseur ?",
    "Quel est le chiffre d'affaires total par ville et par secteur ?",
    "Quel est le client ayant passé le plus de commandes en 2024 ?",
    "Donne la liste des produits commandés uniquement par un seul client.",
    "Quel est le nombre de commandes passées par les clients du secteur 'BTP' ?",
    "Quel est le fournisseur ayant vendu le plus de produits différents ?",
    "Liste les 10 produits les moins commandés.",
    "Quel est le montant total des commandes pour chaque ville et chaque mois ?",
    "Donne la liste des clients n'ayant jamais commandé de produits du fournisseur 'ABC'.",
    "Quel est le montant total des commandes pour chaque trimestre ?",
    "Combien de clients ont commandé au moins une fois chaque année depuis 2020 ?",
    "Quel est le montant total des commandes pour chaque catégorie, chaque année et chaque fournisseur ?",
    "Liste les clients ayant commandé des produits de la catégorie 'Informatique' en 2024.",
    "Quel est le nombre total de commandes pour chaque fournisseur par trimestre ?",
    "Quel est le client ayant commandé le plus de produits différents en 2023 ?",
    "Combien de commandes ont été annulées par mois ?",
    "Quel est le montant total des ventes pour chaque jour de la semaine ?",
    "Quel est le fournisseur ayant généré le plus grand chiffre d'affaires chaque trimestre ?",
    "Combien de produits de la catégorie 'Santé' ont été commandés par les clients du secteur 'Santé' ?",
    "Quel est le client ayant commandé le plus souvent le lundi ?",
    "Quel est le montant total des ventes pour chaque ville chaque trimestre ?",
    "Quel est le produit le plus commandé par les clients du secteur 'Education' ?",
    "Combien de commandes ont été livrées en avance ?",
    "Liste les commandes dont le montant est supérieur à la moyenne des montants de l'année.",
    "Quel est le nombre total de commandes par fournisseur et par ville ?",
    "Quel est le montant total des commandes passées en ligne ?",
    "Quel est le client ayant le montant moyen de commande le plus élevé ?",
    "Combien de fournisseurs différents ont vendu des produits de la catégorie 'Informatique' ?",
    "Quel est le produit ayant été commandé le moins de fois en 2024 ?",
    "Donne la liste des produits qui n'ont jamais été commandés au mois de décembre.",
    "Quel est le chiffre d'affaires total par client pour les commandes de plus de 2000 euros ?",
    "Quel est le montant total des commandes dont la livraison a été annulée ?",
    "Quel est le fournisseur ayant vendu des produits à tous les clients ?",
    "Liste les clients qui ont passé des commandes chaque année depuis 2020.",
    "Combien de commandes ont été passées lors du Black Friday ?",
    "Quel est le nombre de clients par fournisseur ?",
    "Quel est le montant total des ventes réalisées en ligne par fournisseur ?",
    "Quel est le nombre de commandes passées pour chaque combinaison client/produit ?",
    "Quel est le fournisseur ayant vendu le plus grand nombre de produits différents chaque mois ?",
    "Quel est le client ayant commandé chaque mois depuis 2022 ?",
    "Combien de commandes ont été payées en espèces chaque année ?",
    "Quel est le montant moyen des commandes pour chaque jour de la semaine ?",
    "Liste les clients ayant passé des commandes chaque mois et chaque année.",
    "Quel est le produit le plus vendu par ville ?",
    "Quel est le montant total des commandes payées en espèces et en ligne ?",
    "Quel est le client ayant commandé tous les produits en 2024 ?",
    "Quel est le montant total des ventes réalisées pour chaque fournisseur par catégorie de produit ?",
    "Quel est le produit qui n’a jamais été vendu à un client de la ville de Paris ?",
    "Combien de commandes ont été passées par les clients du secteur 'Public' ?",
    "Liste les commandes passées un jour férié.",
    "Quel est le nombre de clients ayant commandé chaque catégorie de produit ?",
    "Quel est le fournisseur ayant généré le plus de chiffre d'affaires en 2023 ?",
    "Quel est le produit le plus commandé par les clients du secteur 'BTP' ?",
    "Donne la liste des produits vendus exclusivement par un seul fournisseur.",
    "Quel est le montant total des commandes pour chaque ville, chaque mois et chaque année ?",
    "Quel est le client ayant commandé le plus de produits chaque année ?",
    "Quel est le montant total des commandes dont le fournisseur est à l'étranger ?",
    "Combien de produits différents ont été commandés chaque trimestre ?",
    "Quel est le chiffre d'affaires total par secteur et par trimestre ?",
    "Quel est le nombre de commandes passées en décembre 2023 ?",
    "Quel est le client ayant commandé le plus de produits de la catégorie 'Bureautique' ?",
    "Combien de produits de chaque catégorie ont été vendus chaque année ?",
    "Quel est le montant total des commandes annulées pour chaque mois ?",
    "Quel est le nombre moyen de commandes par client pour chaque ville ?",
    "Liste les clients n'ayant jamais commandé de produits de la catégorie 'Santé'.",
    "Quel est le fournisseur ayant vendu le moins de produits en 2023 ?",
    "Quel est le nombre total de commandes pour chaque secteur, chaque année et chaque ville ?",
    "Quel est le client ayant commandé chez le plus grand nombre de fournisseurs différents ?",
    "Donne la liste des commandes dont le montant est supérieur à 10 000 euros.",
    "Quel est le chiffre d'affaires total par catégorie et par trimestre ?",
    "Quel est le montant moyen des commandes passées par les clients de la ville de Lyon ?",
    "Liste les produits commandés le dernier jour de chaque trimestre.",
    "Quel est le nombre total de commandes pour chaque catégorie chaque trimestre ?",
    "Quel est le montant total des commandes pour chaque client, chaque ville et chaque année ?",
    "Quel est le client ayant passé le plus de commandes chaque mois en 2024 ?",
    "Quel est le fournisseur dont les produits n'ont jamais été commandés en 2023 ?",
    "Donne la liste des commandes passées par les clients n'ayant jamais commandé en 2023.",
    "Quel est le montant total des commandes pour chaque produit chaque mois ?",
    "Quel est le montant total des ventes pour chaque fournisseur chaque trimestre ?",
    "Liste les clients ayant commandé le même produit plusieurs fois en 2023.",
    "Quel est le nombre total de commandes pour chaque combinaison de client, produit et fournisseur ?",
    "Quel est le montant total des ventes pour chaque produit chaque année ?",
    "Quel est le nombre moyen de commandes passées par mois et par secteur ?",
    "Quel est le montant total des ventes réalisées par les clients du secteur 'Santé' ?",
    "Quel est le client ayant commandé chaque trimestre de 2023 ?",
    "Quel est le montant total des ventes pour chaque catégorie chaque trimestre ?",
    "Quel est le produit ayant été commandé le plus de fois chaque trimestre ?",
    "Quel est le fournisseur ayant le plus de produits référencés chaque année ?",
    "Combien de clients ont passé des commandes chaque trimestre en 2024 ?",
    "Quel est le montant total des ventes réalisées en 2023 par catégorie ?",
    "Quel est le produit le plus vendu à chaque fournisseur ?",
    "Quel est le nombre total de commandes pour chaque secteur chaque mois ?",
    "Quel est le montant total des ventes réalisées chaque jour en 2024 ?",
    "Donne la liste des commandes annulées pour chaque client.",
    "Quel est le client ayant commandé le plus de produits par catégorie ?",
    "Quel est le montant total des ventes réalisées par fournisseur et par ville ?",
    "Quel est le fournisseur ayant vendu des produits à tous les clients du secteur 'Education' ?",
    "Quel est le client ayant commandé le plus de produits de chaque catégorie ?",
    "Liste les commandes passées lors du Cyber Monday.",
    "Quel est le montant total des ventes réalisées en 2024 par fournisseur ?",
    "Donne la liste des produits commandés uniquement par les clients du secteur 'Santé'.",
    "Quel est le montant total des commandes pour chaque client et chaque fournisseur ?",
    "Quel est le nombre moyen de commandes passées par trimestre et par client ?",
    "Combien de commandes ont été passées lors du dernier trimestre de 2023 ?",
    "Quel est le montant total des ventes pour chaque jour de la semaine en 2023 ?",
    "Liste les clients ayant commandé chaque mois et chaque trimestre.",
    "Quel est le fournisseur ayant vendu le plus de produits chaque jour en 2024 ?",
    "Quel est le produit le plus vendu chaque jour en 2024 ?",
    "Quel est le client ayant le plus commandé chaque semaine ?",
    "Quel est le montant total des ventes réalisées en ligne chaque mois ?",
    "Combien de produits différents ont été commandés en décembre 2024 ?",
    "Quel est le fournisseur dont les produits n'ont jamais été commandés par les clients de Paris ?",
    "Quel est le montant total des ventes pour chaque fournisseur chaque année ?",
    "Quel est le client ayant commandé le plus de produits différents chaque trimestre ?",
    "Quel est le montant total des commandes annulées chaque trimestre ?",
    "Donne la liste des produits commandés par chaque client chaque trimestre.",
    "Quel est le montant moyen des commandes pour chaque secteur et chaque année ?",
    "Quel est le nombre total de commandes pour chaque produit chaque semaine ?",
    "Quel est le fournisseur ayant généré le moins de chiffre d'affaires chaque année ?",
    "Quel est le montant total des ventes pour chaque secteur chaque année ?",
]
